name: Ubuntu
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Creating User and Changing the Password
      run: |
        sudo apt install tasksel
        sudo tasksel install kubuntu-full
