name: Ubuntu
on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Enter Your UserName'
        required: true
      passwd:
        description: 'Enter Your Password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Creating User and Changing the Password
      run: |
        sudo useradd -m ${{ github.event.inputs.user }} &> /dev/null
        sudo adduser ${{ github.event.inputs.user }} sudo &> /dev/null
        echo '${{ github.event.inputs.user }}:${{ github.event.inputs.passwd }}' | sudo chpasswd
    - name: Setup Desktop
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install xubuntu-desktop
        sudo apt install xrdp
        sudo adduser xrdp ssl-cert
        systemctl restart xrdp
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Start Ngrok Tunnel
      run: ./ngrok tcp 3389
    - name: Keep Alive
      run: ping -D 10.10.10.10 > logfile.txt
