name: WINDOWS 2019
on:  
  push:
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install VS Code
      run: choco install vscode
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Firewall for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Allow RDP Property from Regdit
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Assign User
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Infantvalan03" -Force)
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Download Ngrok Check 
      run: Invoke-WebRequest https://drive.google.com/uc?id=1A3kIAdbFiSAHHR3MJe1GRMkvsoGL9i2K  -OutFile NGROK-CHECK.bat
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: Downloading Loop File
      run: Invoke-WebRequest https://drive.google.com/uc?id=1CkbYMzm_9TWTDyOiPxbLg4kUfWDzBoaS  -OutFile loop.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat 
