name: CI

on:  
  #push:
  #pull_request:
  workflow_dispatch:
    inputs:
      password:
        description: 'Enter Your Password'
        required: true
      authtoken:
        description: 'Enter Your Ngrok Token'
        required: true
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken ${{ github.event.inputs.authtoken }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Firewall for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Allow RDP Property from Regdit
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Assign User
      run: Set-LocalUser -Name "Windows VPS Free" -Password (ConvertTo-SecureString -AsPlainText "${{ github.event.inputs.password }}" -Force)
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Download Timeout Script
      run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
    - name: Keep Alive
      run: .\a.ps1
